services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./scripts:/app/scripts
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker -w 4 --bind 0.0.0.0:8000 --timeout 120
    deploy:
      resources:
        limits:
          memory: 1g
